### ISSUE TITLE
Specific Item for "currency"

### ISSUE THREAD

**Issue by rosebloom54** [SparklingComet/TradeShop#115]
### Is your feature request related to a problem?

On a server, I'd like to have diamonds or a specific item used as a central currency for buying and selling items. If you want to sell any item, you would have other players pay diamonds. If you want to buy an item from another player, you would give diamonds.

### Describe the solution you'd like.

Having a setting where you can make an item used as the default way to pay for something. Buying something would use the item, and if someone buys from you, it would give them the item.

### Describe alternatives you've considered.

I have looked through other plugins to see if I could manage to find a feature like this, and they are either out of date, or they are just currencies, such as money.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported TradeShop build.
- [X] I have asked the Developers and they have confirmed that it is not already in development.

**Comment by KillerOfPie** [comment]
Will probably add this after 2.4.0 is release, going to put some notes here for other things that also need to be done for thi.

**Comment by KillerOfPie** [comment]
Air, Void_Air, Cave_Air
Need to be moved from Config blacklist to internal blocking

**Comment by KillerOfPie** [comment]
new config section, planned for 2.5.0

```yaml
# |    Item Block Options    |
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
item-block-options:
  # Should we enable Item Blacklist
  enable-blacklist: false
  
  # Should we enable split Item Blacklist (Seperate Cost/Product Blacklists)
  enable-split-blacklist: false
  
  # Should we enable Item Whitelist
  enable-whitelist: false
  
  # Should we enable split Item Whitelist (Seperate Cost/Product Whitelists)
  enable-split-whitelist: false
  
  lists:
    # Material types that cannot be used in trades
    blacklist-items: [Bedrock, Command_Block, Barrier]
    
    # Material types that cannot be used in trades as a Cost
    cost-blacklist-items: []
    
    # Material types that cannot be used in trades as a Product
    product-blacklist-items: []
    
    # Material types that are allowed in trades (Anything not in this list will not be allowed)
    whitelist-items: []
    
    # Material types that are allowed in trades as a Cost (Anything not in this list will not be allowed)
    cost-whitelist-items: [Diamond, Emerald, Gold_Ingot, Iron_Ingot, Gold_Nugget, Iron_Nugget]
    
    # Material types that are allowed in trades as a Product (Anything not in this list will not be allowed)
    product-whitelist-items: []
```

**Comment by KillerOfPie** [comment]
Option 2:

I like this more since you cant have a Blacklist and Whitelist active at the same time. This would allow a general Blacklist then a separate Whitelist or Blacklist for Cost/Product. Should also prevent bad configurations that the amount of options Option 1 allows.

```yaml
# |    Illegal Items Options    |
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
illegal-items-options:
  # Valid Types: DISABLED, BLACKLIST, WHITELIST 

  # List for illegal items for both Cost and Product
  global-illegal-items:
    type: BLACKLIST
    list: [Bedrock, Command_Block, Barrier]

  # List for illegal items for only Cost items
  cost-illegal-items:
    type: WHITELIST
    list: [Diamond, Emerald, Gold_Ingot, Iron_Ingot, Gold_Nugget, Iron_Nugget]

  # List for illegal items for only Product items
  product-illegal-items:
    type: DISABLED
    list: []
```
