### ISSUE TITLE
Sign shop not working

### ISSUE THREAD

**Issue by HossamMohsen7** [SparklingComet/TradeShop#43]
Hello,
I'm using the latest version of TradeShop on spigot 1.12.2. I tried to make a sign shop but it's saying "You need to put a chest under the sign!" even if there was a chest.
Any help?

**Comment by KillerOfPie** [comment]
@7osCraft can I see your config?

**Comment by HossamMohsen7** [comment]
Sure

```yaml
check-updates: true
allowed-shops:
- CHEST
- TRAPPED_CHEST
- SHULKER
allowed-directions:
- DOWN
- WEST
- SOUTH
- EAST
- NORTH
- UP
itrade-shop-name: Server Shop
allow-double-trade: true
allow-quad-trade: true
max-edit-distance: 4
max-shop-users: 5
illegal-items:
- Bedrock
- Command_Block
allow-custom-illegal-items: true
tradeshop-name: Trade
itradeshop-name: iTrade
bitradeshop-name: BiTrade
allow-metrics: true
```
